services:
  banco-agenda:
    image: postgres:16-alpine
    container_name: postgres_agenda_senai
    restart: always
    environment:
      POSTGRES_DB: agenda_senai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password123
    ports:
      - "5433:5432"
    volumes:
      - dados_banco:/var/lib/postgresql/data

volumes:
  dados_banco:


